### ISSUE TITLE
How to deploy this to vsphere IaaS

### ISSUE THREAD

**Issue by yyl8815** [cloudfoundry-community/cf-services-contrib-release#166]
Hi there,
I am trying to deploy all these services onto the cloudfoundry which is deployed on vsphere. However, I don't know to create the manifest. 
Can anyone give me an example manifest file?

**Comment by yyl8815** [comment]
Just as [this doc](https://github.com/cloudfoundry/cf-mysql-release/tree/master) for mysql.

Also, it will be of much help if anyone can tell how to verify if the installation is successful

**Comment by rkoster** [comment]
You should be able to create a manifest by using `./templates/make_manifest vsphere`. 
Running `rspec spec/service_life_cycle_spec.rb` should run some integrations test (it will deploy and application, create service instances, bind said instances to the app and does a write/read exercise for all services). You will have to export [some environment variable](https://github.com/cloudfoundry-community/cf-services-contrib-release/blob/master/spec/spec_helper.rb#L17-L39) because the defaults assume bosh-lite. Please note however that the the contrib-services are using the v1 services API for which [support will soon be dropt form Cloud Foundry](https://www.pivotaltracker.com/story/show/104067222).
